import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import AddVoter from "../components/AddVoter";
import GetVoter from "../components/GetVoter";
import WorkflowStatus from "../components/WorkflowStatus";
import Body from "../components/Body";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header />
        <GetVoter />
        <WorkflowStatus/>
    </div>
  )
}
