import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Body from "../components/Body";

export default function Home() {
console.log(process.env.NEXT_PUBLIC_CONTRACT_ADDRESS)
    return (
    <div className={styles.container} >
      <Head>
        <title>Dapps Voting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Body />
    </div>
  )
}
